from __future__ import annotations

# Camera
CAMERA_TARGET_SIZES = ((1280, 720), (640, 480))
CAMERA_READ_RETRY_LIMIT = 45
CAMERA_REOPEN_COOLDOWN_S = 0.15
CAMERA_LOOP_IDLE_S = 0.0
CAMERA_FAIL_SLEEP_S = 0.001

# Cursor mapper
CURSOR_INNER_RATIO = 0.80
CURSOR_SPEED_NORM_RATIO = 0.05
CURSOR_DEADZONE_BASE = 0.0
CURSOR_DEADZONE_SCALE_FACTOR = 0.0
CURSOR_SOFT_DEADZONE_PX = 3.0

# Gesture
GESTURE_CONFIRM_HOLD_S = 0.04
GESTURE_ACTION_COOLDOWN_S = 0.22
GESTURE_LOCK_S = 0.10
GESTURE_DRAG_ACTIVATE_S = 0.24
GESTURE_DOUBLE_CLICK_WINDOW_S = 0.55
GESTURE_SCROLL_GAIN = 2
GESTURE_Z_TAP_ENTER = -0.06
GESTURE_Z_TAP_EXIT = -0.03
GESTURE_KEYBOARD_AFTER_PINCH_S = 0.0
GESTURE_SCROLL_DIR_SWITCH_COOLDOWN_S = 0.06
GESTURE_RIGHT_CLICK_HOLD_S = 0.08
GESTURE_KEYBOARD_HOLD_S = 0.50

# Hand tracker
HAND_LABEL_MAJORITY_RATIO = 0.72
HAND_LOCK_CONFIDENCE_THRESHOLD = 0.30
HAND_LOCKED_DROP_THRESHOLD = 0.20

# Mouse worker
MOUSE_WORKER_HZ = 240.0
