from __future__ import annotations

# Camera
CAMERA_BACKENDS_WINDOWS = ("MSMF", "DSHOW", "ANY")
CAMERA_TARGET_SIZES = ((1280, 720), (640, 480))
CAMERA_READ_RETRY_LIMIT = 45
CAMERA_REOPEN_COOLDOWN_S = 0.15
CAMERA_LOOP_IDLE_S = 0.002
CAMERA_FAIL_SLEEP_S = 0.005

# Cursor mapper
CURSOR_INNER_RATIO = 0.80
CURSOR_SMOOTH_MIN_ALPHA = 0.06
CURSOR_SMOOTH_MAX_ALPHA = 0.70
CURSOR_SPEED_NORM_RATIO = 0.05
CURSOR_DEADZONE_BASE = 2.0
CURSOR_DEADZONE_SCALE_FACTOR = 0.04

# Gesture
GESTURE_CONFIRM_HOLD_S = 0.18
GESTURE_ACTION_COOLDOWN_S = 0.25
GESTURE_LOCK_S = 0.16
GESTURE_DRAG_ACTIVATE_S = 0.28
GESTURE_DOUBLE_CLICK_WINDOW_S = 0.32
GESTURE_SCROLL_GAIN = 1
GESTURE_Z_TAP_ENTER = -0.06
GESTURE_Z_TAP_EXIT = -0.03

# Mouse worker
MOUSE_WORKER_HZ = 120.0
MOUSE_CURSOR_INTERP_ALPHA = 0.42
